### ISSUE TITLE
how was the tool invoked

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#118]
And maybe add the option to report how the tool was run - manual from command line or through a cron job.

**Comment by ShadowM00n** [comment]
1. Cron runs tasks based on the owner of the crontab file, so I don't even know how we'd attempt this.
2. I don't see any statistical value in this whatsoever.

**Comment by haxmeister** [comment]
Perl has built in tool to test if it has a terminal parent... it's in the POSIX library I believe

**Comment by haxmeister** [comment]
http://www.perlmonks.org/?node_id=472045

**Comment by palica** [comment]
for example if a cronjob sends and email it supplies X-Cron-Env to the mail program. I thought it could be determined some how.

```
To: root@mx
Subject: fcron <systab@mx> test -x /usr/sbin/run-crons && /usr/sbin/run-crons
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <USER=root>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <HOME=/>
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <SHELL=/bin/bash>
Message-Id: <20180416234724.1269C13BDA8@mx>
Date: Tue, 17 Apr 2018 01:47:24 +0200 (CEST)
From: root@mx (fcron)
```

**Comment by palica** [comment]
statistical value would be: "are our users running it once in a while or through cron regularly?"

**Comment by ShadowM00n** [comment]
Even if @haxmeister's method works, I still don't see the value in this; more specifically, I see lots of room for misrepresentation. You could for instance have a person who prefers to run it manually on a regular basis, which would be misinterpreted because it wasn't run from cron, or run from cron sporadically because they reboot a lot or something. How does that help us or the Funtoo dev team?

**Comment by haxmeister** [comment]
I could be possible to have a "report-stats" section that combines these issues. The section could contain the execution time (possibly also for each individual function), and whether the program's STDOUT and STDIN are attached to a terminal (cron or not), and as another idea.. we could have it add a timestamp to the .conf file and therefore it can report how long it has been since it was last run. Though some of this may actually already be done with ES. It is all completely possible and doable.

**Comment by ShadowM00n** [comment]
Just because one *can* doesn't necessarily mean one *should*, is my point. If there's no statistical value in it, is it really worth trying to implement it? The speed idea makes a kind of sense if you want to be super proactive about it, I'll agree, but I honestly can't think of any good reason to have this statistic. It doesn't accurately tell us much as far as I can tell and it doesn't really signal about any sort of problems.

Also, there's already a timestamp in the .conf file, fyi. I added that a few days ago.

**Comment by palica** [comment]
I think @haxmeister meant timestamp of the last run not the config generation timestamp.
But the timestamp can be seen in ES so I wouldn't bother implementing it. Ok, I think then we don't really need it. Going to close it for now. :)
