### ISSUE TITLE
Info Chassis report laptop=notebook and server 

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#17]
see dashboard there are systems reporting as notebook and laptop which I think could be merged. Also the servers didn't report anything. inxi reports it as server. Could you please look into it?

**Comment by haxmeister** [comment]
I updated the chassis options to reflect the full list according to the official standard (it was not exactly correct before). So now we should get more accurate information and no "null" reports. As for reports that show N/A, that can only be those machines that either don't have DMI information or somehow the user can't view the file contents at `/sys/class/dmi/id/chassis_type` . The value N/A means the number extracted from the file (or lack thereof) is 0.. 

ref this chart: (scroll down to the list of chassis types and the number found in the file)
https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.1.1.pdf

Seems to me it might make sense to combine laptop and notebook for the report, if you have time.. you can look at the full list and see if you would also like to combine others.

**Comment by palica** [comment]
Oh, OK I didn't know there was a reference for that. We can leave it like that for now.

I would like to know what the difference between Laptop and Notebook is, though?

**Comment by haxmeister** [comment]
A notebook is intended to go into a backpack or other consumer carry bag. It will usually weigh 3lbs or less and have a screen that is less than 15". A laptop is intended to be as close to a desktop as possible and still be portable. There is typically a considerable performance difference due to space constraints, though the line is blurry.... but you are managing the data. I'm pretty much doing the back end, so if you think the difference isn't significant enough to keep track of I can change them however no problem.

**Comment by palica** [comment]
can leave it like that for now. will see how it does with more users reporting.
