### ISSUE TITLE
move to index with version number included

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#86]
funtoo-2.0.0-2018.03.16 for production
and fundev-2.0.0-2018.03.16 for development

**Comment by tejr** [comment]
I suggest we split `report_time` up into two separate subroutines to accomplish this: `report_time` for what is presently the `long` format, and `report_index` for this new index format. Both will be very simple and plain that way.

**Comment by haxmeister** [comment]
development branch now gives this type of output:
```your report can be seen at: http://elk.liguros.net:9200/fundev-2.0.0-alpha-2018.03.18/report/8WtGO2IByafLPIWA0Z8Z```

where the ```send_report()``` function now checks the ```$VERSION``` in Report.pm and looks for the word "alpha" all lower case. If it finds it, it appends "fundev" to the index name, if it does not.. it appends "funtoo".

As per @palica I changed -dev to -alpha because the word -dev is confusing in the index name.
